### ISSUE TITLE
Evaluate plausible.io for usage tracking

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#83]
If we can, we may prefer to avoid google analytics for privacy reasons. We should evaluate plausible.io to see if it might meet our needs. 

**ACCEPTANCE CRITERIA**
- [x] Spend up to a day evaluating https://plausible.io/
- [x] How much of an improvement would it be for privacy concerns, measured against google analytics?
- [x] How difficult would it be to implement?
- [x] How much would it cost?
- [x] Would it allow us to track how often a dataset has been viewed and/or downloaded?

**Comment by kelynch** [comment]
Research document - https://docs.google.com/document/d/1bqcgcIlxM1-clijhAIU51LfLzQEdyqyyF9fJkiVNElU/edit#heading=h.bsmas9g4txvg
